spring:
  application:
    name: axon-messaging
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

axon:
  serializer:
    events: jackson
    general: jackson
    messages: jackson
  axonserver:
    servers: localhost:8124
