version: '3.7'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  axon-server:
    image: axoniq/axonserver:2023.2.3
    ports:
      - "8024:8024"
      - "8124:8124"
    environment:
      - AXONIQ_AXONSERVER_HOSTNAME=axon-server
      - AXONIQ_AXONSERVER_STANDALONE=true
      - axoniq.axonserver.accesscontrol.enabled=false

  posts-command:
    image: dev/posts-command
    ports:
      - "81:8080"
    environment:
      - host.axon=axon-server
    depends_on:
      - axon-server

  posts-aggregate:
    image: dev/posts-aggregate
    environment:
      - host.axon=axon-server
    depends_on:
      - axon-server

  posts-projection:
    image: dev/posts-projection
    ports:
      - "80:8080"
    environment:
      - host.axon=axon-server
      - host.db=postgres
    depends_on:
      - axon-server
      - postgres

  profanity-service:
    image: dev/profanity-service
    environment:
      - host.axon=axon-server
    depends_on:
      - axon-server

  spammer-app:
    image: dev/spammer-app
    environment:
      - host.axon=axon-server
    depends_on:
      - axon-server

  spammer:
    build: .
    depends_on:
      - spammer-app
    command:
      - "40"
      - "60"
      - http://spammer-app:8080