version: '3.7'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  axon-server:
    image: axoniq/axonserver:latest
    ports:
      - "8024:8024"
      - "8124:8124"
    environment:
      - AXONIQ_AXONSERVER_HOSTNAME=axon-server
      - AXONIQ_AXONSERVER_STANDALONE=true
      - axoniq.axonserver.accesscontrol.enabled=false

  cqrs-public:
    image: dev/axon-cqrs
    ports:
      - "80:8080"
    environment:
      - host.db=postgres
      - host.axon=axon-server
    depends_on:
      - axon-server
      - postgres

  cqrs-workers:
    image: dev/axon-cqrs
    depends_on:
      - cqrs-public
    environment:
      - host.db=postgres
      - host.axon=axon-server

  spammer:
    build: .
    depends_on:
      - cqrs-public
    command:
      - "10"
      - "3"
      - http://cqrs-public:8080